FROM python:3.9

RUN apt update && apt install nginx git -y

ENV PYTHONPATH=/app:${PYTHONPATH}
ENV PATH=/app:${PATH}

RUN mkdir -p /app/service
WORKDIR /app

ADD setup.py README.md /app/service/
RUN cd service && pip install -e .[production]
ADD . ./service

CMD ["uvicorn", "service.app:app", "--host", "0.0.0.0", "--port", "5000"]