FROM python:3
ARG TOKEN
RUN apt update && apt install nginx git -y

RUN mkdir -p /root/.pip
ADD pip.conf /root/.pip/pip.conf
ENV PYTHONPATH=/app:${PYTHONPATH}
ENV PATH=/app:${PATH}

RUN mkdir -p /app/service
WORKDIR /app

ADD setup.py README.md /app/service/
RUN cd service && pip install -e .[production] --use-deprecated=legacy-resolver
ADD nginx.conf /etc/nginx/nginx.conf
ADD entrypoint.sh .
RUN chmod +x ./entrypoint.sh
ADD wsgi.ini .
ADD . ./service

CMD /app/entrypoint.sh
